"""`SyncReceipt`: a write queued on a phone lands once, however often it is sent.

`docs/offline.md` D3, and OPEN-2 as decided in review: a table with a unique key
rather than a key column on each written row. `a_queued_write_lands_once` is the
mechanism, not a backstop; `sync.receipts.once()` inserts into it before the
write it guards, so a second copy of the write waits on this index.
"""

# Generated by Django 5.2.17 on 2026-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField(editable=False)),
                ("made_by_id", models.PositiveBigIntegerField()),
                ("write", models.CharField(max_length=255)),
                ("request", models.JSONField()),
                ("status", models.PositiveSmallIntegerField(null=True)),
                ("answer", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key",), name="a_queued_write_lands_once"
                    )
                ],
            },
        ),
    ]
