"""A receipt keeps no answer: a write that arrives again is told it is already saved.

#161. The first arrival's answer described the cell, or the register, as it was
then; handed to a replay it was drawn as it is now. `sync.receipts` answers a
replay "already saved" with no cell data, so nothing reads these columns.
"""

# Generated by Django 5.2.17 on 2026-09-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_a_queued_write_lands_once"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncreceipt",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="syncreceipt",
            name="status",
        ),
    ]
