# Generated by Django 5.2.17 on 2026-09-05 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_classteacher"),
        ("fees", "0002_ledger_is_append_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeConcession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_membership_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="accounts.Membership id of the student's STUDENT membership. A bare id and not a ForeignKey — see FeeLedgerEntry and docs/tenancy.md.",
                    ),
                ),
                (
                    "amount_kobo",
                    models.PositiveBigIntegerField(
                        help_text="Whole kobo, a magnitude. The ledger applies the sign."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text='Why it was granted — "Staff child", "Bursary 2026". Becomes the narration.',
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="A concession no longer granted. Switched off rather than deleted, because the entries it produced name it.",
                    ),
                ),
                (
                    "granted_by_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="accounts.User id of whoever granted it, where there was one.",
                        null=True,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student_membership_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["class_group_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeeScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="What this line is for, in the school's words. Becomes the narration.",
                        max_length=255,
                    ),
                ),
                (
                    "amount_kobo",
                    models.PositiveBigIntegerField(
                        help_text="Whole kobo, a magnitude. The ledger applies the sign."
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Print order on the bill, smallest first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="feeledgerentry",
            name="a_charge_increases_what_is_owed",
        ),
        migrations.AlterField(
            model_name="feeledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("charge", "Charge"),
                    ("payment", "Payment"),
                    ("discount", "Discount"),
                    ("reversal", "Reversal"),
                    ("refund", "Refund"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="feeconcession",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_kobo__gt", 0)),
                name="a_concession_reduces_something",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeconcession",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason__regex", "\\S")),
                name="a_concession_says_why",
            ),
        ),
        migrations.AddField(
            model_name="feeledgerentry",
            name="source_concession",
            field=models.ForeignKey(
                blank=True,
                help_text="The concession that posted this discount, where one did.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="fees.feeconcession",
            ),
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="class_group",
            field=models.ForeignKey(
                help_text="The class this bill is for.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_schedules",
                to="academics.classgroup",
            ),
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="term",
            field=models.ForeignKey(
                help_text="The term this bill is for.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_schedules",
                to="academics.term",
            ),
        ),
        migrations.AddField(
            model_name="feescheduleline",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="fees.feeschedule",
            ),
        ),
        migrations.AddField(
            model_name="feeledgerentry",
            name="source_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The schedule line that posted this charge, where one did.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="fees.feescheduleline",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ("charge", "refund")), _negated=True),
                    ("amount_kobo__gt", 0),
                    _connector="OR",
                ),
                name="a_charge_or_refund_increases_what_is_owed",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "charge"), ("source_line__isnull", False)),
                fields=("student_membership_id", "source_line"),
                name="a_schedule_line_charges_a_child_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "discount"), ("source_concession__isnull", False)
                ),
                fields=("student_membership_id", "term", "source_concession"),
                name="a_concession_discounts_a_child_once_per_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_line__isnull", True),
                    ("kind__in", ("charge", "reversal")),
                    _connector="OR",
                ),
                name="a_schedule_line_only_produces_charges",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_concession__isnull", True),
                    ("kind__in", ("discount", "reversal")),
                    _connector="OR",
                ),
                name="a_concession_only_produces_discounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_concession__isnull", False),
                    ("source_line__isnull", False),
                    _negated=True,
                ),
                name="an_entry_has_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                fields=("term", "class_group"),
                name="one_fee_schedule_per_class_per_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="feescheduleline",
            constraint=models.UniqueConstraint(
                fields=("schedule", "description"), name="a_bill_names_each_line_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="feescheduleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_kobo__gt", 0)),
                name="a_schedule_line_charges_something",
            ),
        ),
    ]
