# Generated by Django 5.2.17 on 2026-09-29 16:44

import django.utils.timezone
from django.db import migrations, models



FUNCTION = """
CREATE OR REPLACE FUNCTION fees_paystack_record_is_fixed() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        '% is never edited or deleted; % is not allowed.', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

TRIGGERS = """
CREATE TRIGGER fees_virtual_account_fixed
BEFORE UPDATE OR DELETE ON fees_virtualaccount
FOR EACH ROW EXECUTE FUNCTION fees_paystack_record_is_fixed();

CREATE TRIGGER fees_unmatched_payment_fixed
BEFORE UPDATE OR DELETE ON fees_unmatchedpayment
FOR EACH ROW EXECUTE FUNCTION fees_paystack_record_is_fixed();
"""

DROP_TRIGGERS = """
DROP TRIGGER IF EXISTS fees_unmatched_payment_fixed ON fees_unmatchedpayment;
DROP TRIGGER IF EXISTS fees_virtual_account_fixed ON fees_virtualaccount;
"""
DROP_FUNCTION = "DROP FUNCTION IF EXISTS fees_paystack_record_is_fixed();"

class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0007_a_school_connects_a_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmatchedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("amount_kobo", models.BigIntegerField()),
                ("account_number", models.CharField(blank=True, max_length=32)),
                ("customer_code", models.CharField(blank=True, max_length=64)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("no_account", "No virtual account here has that number"),
                            (
                                "not_a_student",
                                "The account's child is not a student here",
                            ),
                            (
                                "wrong_customer",
                                "Paystack says a different customer paid into it",
                            ),
                            (
                                "no_current_term",
                                "The school has no current term to record it in",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_kobo__gt", 0)),
                        name="an_unmatched_payment_is_money",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_membership_id", models.PositiveBigIntegerField(unique=True)),
                ("customer_code", models.CharField(max_length=64)),
                ("account_number", models.CharField(max_length=10, unique=True)),
                ("account_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=120)),
                ("split_code", models.CharField(max_length=64)),
                (
                    "created_by_id",
                    models.PositiveBigIntegerField(help_text="accounts.User id."),
                ),
                ("created_by_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("account_number__regex", "^[0-9]{10}$")),
                        name="a_virtual_account_is_ten_digits",
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=FUNCTION, reverse_sql=DROP_FUNCTION),
        migrations.RunSQL(sql=TRIGGERS, reverse_sql=DROP_TRIGGERS),
    ]
