# Generated by Django 5.2.17 on 2026-09-29 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models



# `0008` made `fees_paystack_record_is_fixed()`; the same refusal, on the new table.
TRIGGER = """
CREATE TRIGGER fees_unmatched_placement_fixed
BEFORE UPDATE OR DELETE ON fees_unmatchedplacement
FOR EACH ROW EXECUTE FUNCTION fees_paystack_record_is_fixed();
"""
DROP_TRIGGER = "DROP TRIGGER IF EXISTS fees_unmatched_placement_fixed ON fees_unmatchedplacement;"

class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0008_paystack_virtual_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmatchedPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_membership_id", models.PositiveBigIntegerField()),
                ("student_name", models.CharField(max_length=255)),
                (
                    "placed_by_id",
                    models.PositiveBigIntegerField(help_text="accounts.User id."),
                ),
                ("placed_by_name", models.CharField(max_length=255)),
                ("placed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement",
                        to="fees.feeledgerentry",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement",
                        to="fees.unmatchedpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RunSQL(sql=TRIGGER, reverse_sql=DROP_TRIGGER),
    ]
