"""The guardian record, the channel it is reached on, and the code that proves it.

PR B of parent access; `docs/parent-access.md` D9 and D10. Three tables in the
public schema, like everything else in `accounts` — one `GuardianAccount` per
guardian for the whole platform, not one per school.

## The constraint that is the decision

`one_live_contact_per_guardian` is a **partial** unique index, on `guardian`
where `revoked_at IS NULL`. D9 gives a guardian *a* channel, singular, and D11
changes one by revoking the old binding and verifying the new — a replacement,
not an addition. Until that flow exists this refuses a second live channel
outright, which is the right failure: two live channels would be two answers to
"how do we reach this person", and the system would pick one by ordering.

## The unique constraint that is deliberately absent

There is **no** unique index on `value`. One handset per household is ordinary
among the parents this is built for, so two guardians must be able to hold one
number. `schools.models.Invitation` already records the same trap. It is also
why the channel could not live on `User.phone`, which is `unique=True` and would
have refused the second parent outright.

`code_hash` is likewise not unique: a six-digit code has a million values, so
collisions across channels are expected rather than exceptional, and every
lookup is scoped to a contact row instead. See `GuardianContactCode`.

## The two indexes on code rows, and why the rows are the rate limit

`GuardianContactCode` is the send log — one row per code minted — so
`guardian_contacts._assert_within_send_limits()` bounds sending by *counting
these rows* in a window rather than by folding into a counter somebody
increments (operating rule 4). `(contact, created_at)` and
`(requested_by_school, created_at)` are what make each of those counts an index
scan instead of a walk of every code ever issued.

`requested_by_school` is nullable: platform staff are behind no school, and
neither is a guardian-initiated resend once sign-in exists. Such a send is still
counted against its channel, which is the limit that protects the handset.

## Append-only is not here

It is `0011_a_contact_channel_is_append_only`, a trigger, because operating rule
3 says immutability lives in the database and because the rule this table needs
— every column frozen except two one-way stamps — is not a `CheckConstraint`:
it compares NEW against OLD.
"""

# Generated by Django 5.2.17 on 2026-09-15 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_a_guardianship_pins_the_membership_under_it"),
        ("schools", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The person. One guardian account per login, forever.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GuardianContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=8
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Normalized before it is stored: E.164 for a phone, lowercased domain for an email. Never what was typed.",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_contacts_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="accounts.guardianaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GuardianContactCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("spent", "Spent"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codes",
                        to="accounts.guardiancontact",
                    ),
                ),
                (
                    "requested_by_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_verification_codes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="guardiancontact",
            index=models.Index(fields=["value"], name="accounts_gu_value_a18dcc_idx"),
        ),
        migrations.AddConstraint(
            model_name="guardiancontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("guardian",),
                name="one_live_contact_per_guardian",
            ),
        ),
        migrations.AddIndex(
            model_name="guardiancontactcode",
            index=models.Index(
                fields=["contact", "status"], name="accounts_gu_contact_64ba30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardiancontactcode",
            index=models.Index(
                fields=["contact", "created_at"], name="accounts_gu_contact_0911e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardiancontactcode",
            index=models.Index(
                fields=["requested_by_school", "created_at"],
                name="accounts_gu_request_866343_idx",
            ),
        ),
    ]
