# Generated by Django 5.2.17 on 2026-09-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_a_contact_channel_is_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signinattempts",
            name="scope",
            field=models.CharField(
                choices=[
                    ("identifier", "Identifier"),
                    ("address", "Network address"),
                    ("channel", "Guardian contact channel"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GuardianSignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offered",
                    models.ManyToManyField(
                        help_text="Every guardian the typed value resolved to, including the one picked. One entry is the ordinary case; two is a shared handset.",
                        related_name="sign_ins_offered",
                        to="accounts.guardianaccount",
                    ),
                ),
                (
                    "picked",
                    models.ForeignKey(
                        help_text="The guardian this session was opened as.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sign_ins",
                        to="accounts.guardianaccount",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        help_text="The answered code that proved control of the handset.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sign_ins",
                        to="accounts.guardiancontactcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proof",), name="one_session_per_answered_code"
                    )
                ],
            },
        ),
    ]
