# Generated by Django 5.2.17 on 2026-09-23 17:51

"""What a school typed when it linked a guardian, kept on the link.

#135: a contact can resolve to a guardian who is somebody else's parent. Until
that guardian is live at this school, this school is shown what it typed, not
the `User`'s stored name or channel. Blank on every link made before this.

A database default as well as a Python one, because this table's rules are
tested by raw INSERTs that never reach `save()`.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_a_guardian_session_says_who_was_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianship",
            name="entered_contact",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="guardianship",
            name="entered_name",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
    ]
