"""A guardian may hold one live channel of each type: an email and a phone. #111.

One school reported that its guardians give both on the admission form and
both are live. The index `one_live_contact_per_guardian` refused the second.
Decided 2026-09-24: one live contact per guardian **per channel type**, and a
code goes to the channel the guardian typed (`accounts.guardian_signin`).
"""

# Generated by Django 5.2.17 on 2026-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_what_the_school_typed_for_a_guardian"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="guardiancontact",
            name="one_live_contact_per_guardian",
        ),
        migrations.AddConstraint(
            model_name="guardiancontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("guardian", "channel_type"),
                name="one_live_contact_per_guardian_per_channel",
            ),
        ),
    ]
