"""What a school tells families, written once. docs/messaging.md D6, D9.

`Notice` is the decision, `NoticeClaim` the send (claimed before the provider is
called, one per notice: at most once), `NoticeOutcome` what the provider said.
All three append-only at both layers. `NoticeSettings` is the school's switch,
off by default, one row.
"""

# Generated by Django 5.2.17 on 2026-09-25 13:30

import django.db.models.deletion
from django.db import migrations, models


NOTICE_FUNCTION = """
CREATE OR REPLACE FUNCTION notices_notices_are_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'notices_notice is append-only; % is not allowed. It is what this school decided to tell a family.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

NOTICE_TRIGGER = """
CREATE TRIGGER notices_notices_append_only
BEFORE UPDATE OR DELETE ON notices_notice
FOR EACH ROW EXECUTE FUNCTION notices_notices_are_append_only();
"""

NOTICE_DROP = """
DROP TRIGGER IF EXISTS notices_notices_append_only ON notices_notice;
DROP FUNCTION IF EXISTS notices_notices_are_append_only();
"""

NOTICECLAIM_FUNCTION = """
CREATE OR REPLACE FUNCTION notices_claims_are_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'notices_noticeclaim is append-only; % is not allowed. It is what went, and it went once.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

NOTICECLAIM_TRIGGER = """
CREATE TRIGGER notices_claims_append_only
BEFORE UPDATE OR DELETE ON notices_noticeclaim
FOR EACH ROW EXECUTE FUNCTION notices_claims_are_append_only();
"""

NOTICECLAIM_DROP = """
DROP TRIGGER IF EXISTS notices_claims_append_only ON notices_noticeclaim;
DROP FUNCTION IF EXISTS notices_claims_are_append_only();
"""

NOTICEOUTCOME_FUNCTION = """
CREATE OR REPLACE FUNCTION notices_outcomes_are_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'notices_noticeoutcome is append-only; % is not allowed. It is what the provider said.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

NOTICEOUTCOME_TRIGGER = """
CREATE TRIGGER notices_outcomes_append_only
BEFORE UPDATE OR DELETE ON notices_noticeoutcome
FOR EACH ROW EXECUTE FUNCTION notices_outcomes_are_append_only();
"""

NOTICEOUTCOME_DROP = """
DROP TRIGGER IF EXISTS notices_outcomes_append_only ON notices_noticeoutcome;
DROP FUNCTION IF EXISTS notices_outcomes_are_append_only();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_classteacher"),
        ("results", "0025_a_release_says_its_check_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("result_notice", "Result notice"),
                            ("fee_reminder", "Fee reminder"),
                        ],
                        max_length=16,
                    ),
                ),
                ("student_membership_id", models.PositiveBigIntegerField()),
                ("guardian_user_id", models.PositiveBigIntegerField()),
                ("contact_id", models.PositiveBigIntegerField()),
                ("channel_type", models.CharField(max_length=8)),
                ("address", models.CharField(max_length=254)),
                ("segments", models.PositiveSmallIntegerField()),
                ("send_after", models.DateTimeField()),
                ("created_by_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="results.releasedcard",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="academics.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticeClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_kind", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim",
                        to="notices.notice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoticeOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "said",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted by the provider"),
                            ("refused", "Refused by the provider"),
                            ("unavailable", "Provider unavailable"),
                            ("not_configured", "No provider configured"),
                            ("no_longer_reachable", "No longer reachable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome",
                        to="notices.noticeclaim",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoticeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_notices", models.BooleanField(default=False)),
                ("fee_reminders", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)),
                        name="notice_settings_are_one_row",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["send_after"], name="notices_not_send_af_eb9283_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.UniqueConstraint(
                fields=("card", "contact_id"),
                name="a_card_is_announced_to_a_contact_once",
            ),
        ),
        migrations.RunSQL(sql=NOTICE_FUNCTION, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=NOTICE_TRIGGER, reverse_sql=NOTICE_DROP),
        migrations.RunSQL(sql=NOTICECLAIM_FUNCTION, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=NOTICECLAIM_TRIGGER, reverse_sql=NOTICECLAIM_DROP),
        migrations.RunSQL(sql=NOTICEOUTCOME_FUNCTION, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=NOTICEOUTCOME_TRIGGER, reverse_sql=NOTICEOUTCOME_DROP),
    ]
