"""A fee reminder states what is owed. docs/messaging.md D10, M3.

`Notice.amount_kobo` is the child's whole account as the ledger folded it when
the bursar pressed send. A notice is either about a card with no amount, or an
amount owing about no card, and the check constraint says so. `balance_changed`
is the outcome of a reminder whose account moved before it went.
"""

# Generated by Django 5.2.17 on 2026-09-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_classteacher"),
        ("notices", "0001_a_school_tells_families_once"),
        ("results", "0025_a_release_says_its_check_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="amount_kobo",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noticeoutcome",
            name="said",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted by the provider"),
                    ("refused", "Refused by the provider"),
                    ("unavailable", "Provider unavailable"),
                    ("not_configured", "No provider configured"),
                    ("no_longer_reachable", "No longer reachable"),
                    ("balance_changed", "Balance changed before sending"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount_kobo__isnull", True),
                        ("card__isnull", False),
                        ("kind", "result_notice"),
                    ),
                    models.Q(
                        ("amount_kobo__gt", 0),
                        ("card__isnull", True),
                        ("kind", "fee_reminder"),
                    ),
                    _connector="OR",
                ),
                name="a_notice_is_about_a_card_or_an_amount_owing",
            ),
        ),
    ]
