"""A payment posts its own receipt. docs/messaging.md.

`record_payment()` writes a `Notice` of this kind itself, to the guardians who
receive invoices, when `NoticeSettings.payment_receipts` is on. `source_entry`
is the ledger entry it is about — a real key, same schema, like `card` — and
the check constraint now names three shapes a notice can take instead of two.
`created_by_id` becomes nullable for the entries an import posts with nobody
behind them, the way `attendance.Register.taken_by_id` already is.
"""

# Generated by Django 5.2.17 on 2026-09-28 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_classteacher"),
        ("fees", "0006_a_concession_is_never_edited"),
        ("notices", "0002_a_reminder_states_what_is_owed"),
        ("results", "0027_the_card_carries_the_schools_crest_and_colour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notice",
            name="a_notice_is_about_a_card_or_an_amount_owing",
        ),
        migrations.AddField(
            model_name="notice",
            name="source_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_notices",
                to="fees.feeledgerentry",
            ),
        ),
        migrations.AddField(
            model_name="noticesettings",
            name="payment_receipts",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notice",
            name="created_by_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("result_notice", "Result notice"),
                    ("fee_reminder", "Fee reminder"),
                    ("payment_receipt", "Payment receipt"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.UniqueConstraint(
                fields=("source_entry", "contact_id"),
                name="a_payment_is_receipted_to_a_contact_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount_kobo__isnull", True),
                        ("card__isnull", False),
                        ("kind", "result_notice"),
                        ("source_entry__isnull", True),
                    ),
                    models.Q(
                        ("amount_kobo__gt", 0),
                        ("card__isnull", True),
                        ("kind", "fee_reminder"),
                        ("source_entry__isnull", True),
                    ),
                    models.Q(
                        ("amount_kobo__gt", 0),
                        ("card__isnull", True),
                        ("kind", "payment_receipt"),
                        ("source_entry__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="a_notice_is_about_a_card_an_amount_or_a_payment",
            ),
        ),
    ]
