"""A register posts its own absence alert. docs/messaging.md D14.

`attendance.services.take_register()` writes a `Notice` of this kind itself,
to every live guardian, when `NoticeSettings.absence_alerts` is on.
`source_register` is the register it is about — a real key, same schema, like
`card` and `source_entry`. One register covers a whole class, so the dedup
constraint is a triple (register, child, contact), not a pair.
"""

# Generated by Django 5.2.17 on 2026-09-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_classteacher"),
        ("attendance", "0002_what_too_often_absent_means"),
        ("fees", "0006_a_concession_is_never_edited"),
        ("notices", "0003_a_payment_posts_its_own_receipt"),
        ("results", "0027_the_card_carries_the_schools_crest_and_colour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notice",
            name="a_notice_is_about_a_card_an_amount_or_a_payment",
        ),
        migrations.AddField(
            model_name="notice",
            name="source_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="absence_alerts",
                to="attendance.register",
            ),
        ),
        migrations.AddField(
            model_name="noticesettings",
            name="absence_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("result_notice", "Result notice"),
                    ("fee_reminder", "Fee reminder"),
                    ("payment_receipt", "Payment receipt"),
                    ("absence_alert", "Absence alert"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.UniqueConstraint(
                fields=("source_register", "student_membership_id", "contact_id"),
                name="an_absence_is_told_to_a_contact_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount_kobo__isnull", True),
                        ("card__isnull", False),
                        ("kind", "result_notice"),
                        ("source_entry__isnull", True),
                        ("source_register__isnull", True),
                    ),
                    models.Q(
                        ("amount_kobo__gt", 0),
                        ("card__isnull", True),
                        ("kind", "fee_reminder"),
                        ("source_entry__isnull", True),
                        ("source_register__isnull", True),
                    ),
                    models.Q(
                        ("amount_kobo__gt", 0),
                        ("card__isnull", True),
                        ("kind", "payment_receipt"),
                        ("source_entry__isnull", False),
                        ("source_register__isnull", True),
                    ),
                    models.Q(
                        ("amount_kobo__isnull", True),
                        ("card__isnull", True),
                        ("kind", "absence_alert"),
                        ("source_entry__isnull", True),
                        ("source_register__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="a_notice_is_about_a_card_an_amount_a_payment_or_an_absence",
            ),
        ),
    ]
