"""The proprietor's daily money summary. docs/messaging.md D15.

`MoneySummarySent` is a send log, not a `Notice`: the recipient is staff, by
their own login email, and there is no guardian channel to check. One row per
day, so `manage.py send_daily_money_summary` sends nothing twice.
"""

# Generated by Django 5.2.17 on 2026-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0004_a_register_posts_its_own_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneySummarySent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("for_day", models.DateField(unique=True)),
                ("collected_kobo", models.BigIntegerField()),
                ("billed_kobo", models.BigIntegerField()),
                ("payments", models.PositiveIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="noticesettings",
            name="daily_money_summary",
            field=models.BooleanField(default=False),
        ),
    ]
