"""Who gets the daily money summary: the settings screen. docs/messaging.md D15.

`MoneySummaryRecipient` is a bare id into `accounts.Membership`, for the same
tenancy reason `Notice.student_membership_id` is: nobody by default, and the
school picks its own staff from its live roster.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0005_the_proprietors_daily_money_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneySummaryRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_id", models.PositiveBigIntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
