"""A code is sent once, and what happened to it is written down. docs/messaging.md D5, D6.

`CodeDelivery` is the claim a worker writes before it calls a provider, and its
one-to-one with the code is what makes a second run a no-op. `CodeDeliveryOutcome`
is what the provider said. Both are append-only at both layers, as every record
on this platform is: a trigger refuses what never calls `save()`, and each
trigger's sentence names its table and the operation, so a test can name the
refusal rather than accept any (#89).

`FakeMessage` is the fake provider's outbox. It holds codes in the clear, which
is why `messaging.E001` refuses a deploy with DEBUG off that points at the fake.
"""

# Generated by Django 5.2.17 on 2026-09-25 12:48

import django.db.models.deletion
from django.db import migrations, models


# Spelled out, not built by a helper: `tests/test_refusals_are_constraints`
# reads every RAISE in a migration as a string literal, and an f-string splits
# at its placeholders.
DELIVERIES = """
CREATE OR REPLACE FUNCTION messaging_code_deliveries_are_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'messaging_codedelivery is append-only; % is not allowed. It is the '
        'claim that a code went out once.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

DELIVERIES_TRIGGER = """
CREATE TRIGGER messaging_code_deliveries_append_only
BEFORE UPDATE OR DELETE ON messaging_codedelivery
FOR EACH ROW EXECUTE FUNCTION messaging_code_deliveries_are_append_only();
"""

DELIVERIES_DROP = """
DROP TRIGGER IF EXISTS messaging_code_deliveries_append_only ON messaging_codedelivery;
DROP FUNCTION IF EXISTS messaging_code_deliveries_are_append_only();
"""

OUTCOMES = """
CREATE OR REPLACE FUNCTION messaging_code_delivery_outcomes_are_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'messaging_codedeliveryoutcome is append-only; % is not allowed. It is '
        'what the provider said.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

OUTCOMES_TRIGGER = """
CREATE TRIGGER messaging_code_delivery_outcomes_append_only
BEFORE UPDATE OR DELETE ON messaging_codedeliveryoutcome
FOR EACH ROW EXECUTE FUNCTION messaging_code_delivery_outcomes_are_append_only();
"""

OUTCOMES_DROP = """
DROP TRIGGER IF EXISTS messaging_code_delivery_outcomes_append_only ON messaging_codedeliveryoutcome;
DROP FUNCTION IF EXISTS messaging_code_delivery_outcomes_are_append_only();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_what_the_school_typed_for_a_guardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_type", models.CharField(max_length=8)),
                ("address", models.CharField(max_length=254)),
                ("kind", models.CharField(max_length=32)),
                ("subject", models.CharField(blank=True, max_length=128)),
                ("text", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=128)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted by the provider"),
                            ("refused", "Refused by the provider"),
                            ("unavailable", "Provider unavailable"),
                            ("not_configured", "No provider configured"),
                            ("expired", "Expired before it could be sent"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CodeDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("channel_check", "Channel check"),
                            ("sign_in_code", "Sign-in code"),
                            ("reactivation", "Reactivation"),
                            ("school_answer", "School answer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("channel_type", models.CharField(max_length=8)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="accounts.guardiancontactcode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodeDeliveryOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted by the provider"),
                            ("refused", "Refused by the provider"),
                            ("unavailable", "Provider unavailable"),
                            ("not_configured", "No provider configured"),
                            ("expired", "Expired before it could be sent"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome",
                        to="messaging.codedelivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(sql=DELIVERIES, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=DELIVERIES_TRIGGER, reverse_sql=DELIVERIES_DROP),
        migrations.RunSQL(sql=OUTCOMES, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=OUTCOMES_TRIGGER, reverse_sql=OUTCOMES_DROP),
    ]
