"""D17: `FakeProvider` records the `Reply-To` it was handed too."""

# Generated by Django 5.2.17 on 2026-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_a_code_is_sent_once"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakemessage",
            name="reply_to",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
