# Generated by Django 5.2.17 on 2026-10-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0003_where_a_paper_prints"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("business", "Business"),
                    ("humanities", "Humanities"),
                    ("science", "Science & Mathematics"),
                    ("technology", "Technology"),
                    ("trade", "Trade"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
