# Generated by Django 5.2.17 on 2026-09-23 17:51

"""An invitation remembers the address the admin typed.

The staff screen lists invitations, and the only "who" it may show is what the
inviting school typed: the account an address resolved to can hold another
school's name for that person, and a second identifier (`api.InvitationOut`).
Invitations issued before this show "-".
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="sent_to",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
    ]
