"""A school's own contact email — where a reply to its outgoing mail should land.

`docs/messaging.md` D17: every email this platform sends on a school's behalf
now carries this as `Reply-To`. Blank until the office sets it up.
"""

# Generated by Django 5.2.17 on 2026-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_an_invitation_remembers_what_was_typed"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
