# Generated by Django 5.2.17 on 2026-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_a_school_has_its_own_address_to_write_back_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="school",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
