# Generated by Django 5.2.17 on 2026-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_paystack_virtual_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="lga",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
