# Generated by Django 5.2.17 on 2026-10-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_a_school_names_its_local_government_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
