# Generated by Django 5.2.17 on 2026-08-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_classgroup_classplacement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_membership_id",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                (
                    "assigned_by_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_teachers",
                        to="academics.classgroup",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_teachers",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["class_group", "term"],
                "indexes": [
                    models.Index(
                        fields=["class_group", "term"],
                        name="academics_c_class_g_f72619_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_group", "term"),
                        name="one_class_teacher_per_group_per_term",
                    )
                ],
            },
        ),
    ]
