# Generated by Django 5.2.17 on 2026-10-03 22:50

import datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_classteacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_membership_id", models.PositiveBigIntegerField(unique=True)),
                ("learner_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("female", "Female"), ("male", "Male")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("photo", models.BinaryField(blank=True, null=True)),
                (
                    "updated_by_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student_membership_id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Upper("learner_id"),
                        condition=models.Q(("learner_id", ""), _negated=True),
                        name="one_child_per_learner_id_per_school",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sex__in", ["", "female", "male"])),
                        name="a_childs_sex_is_female_male_or_unsaid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_of_birth__isnull", True),
                            ("date_of_birth__gte", datetime.date(1950, 1, 1)),
                            _connector="OR",
                        ),
                        name="a_date_of_birth_is_this_century_or_last",
                    ),
                ],
            },
        ),
    ]
