"""The register: the fact one was taken, and one child's entry in it.

Phase 2, slice 1. Two tables rather than one, because a single table keyed on
`(student, date, period)` cannot tell "nobody took a register" from "a register
was taken and this child was skipped" — see `attendance.models` for the long
form and `results.TermAbsence` for where this codebase decided the same thing
the first time.

Three constraints, and each is a rule that would otherwise live only in Python
and be walked around by a data import, a shell session or a future service
function:

- `one_register_per_group_per_period` — one register per group per period per
  day. Also the backstop for two teachers submitting the same register at the
  same instant, which `services._locked_register()` recovers from by re-reading
  under the lock rather than failing.
- `a_period_is_numbered_from_one` — a zeroth period is an off-by-one arriving
  from a client, and it would sort ahead of the morning register, which is the
  row the card's day rule reads.
- `one_mark_per_student_per_register` — one entry per child per register.

**No append-only trigger on either table, unlike every frozen table in
`results`.** A register corrected on the day is a register, not a falsified
record. What must not move is the card, and `results.ReleasedCard` already
refuses an UPDATE at two layers.

**The rule that is not here**: a register's date must fall inside its term. A
`CheckConstraint` cannot reference `academics_term.starts_on`, because a check
constraint sees one row of one table, so that rule lives in
`services.DayOutsideTheTerm` and the absence is recorded rather than left to be
discovered. `docs/attendance.md`, correctness requirement 6.
"""

# Generated by Django 5.2.17 on 2026-09-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_classteacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_on", models.DateField()),
                ("period", models.PositiveSmallIntegerField(default=1)),
                ("taken_by_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="academics.classgroup",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_on", "period", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_membership_id",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        max_length=16,
                    ),
                ),
                ("marked_by_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks",
                        to="attendance.register",
                    ),
                ),
            ],
            options={
                "ordering": ["register", "student_membership_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="register",
            constraint=models.UniqueConstraint(
                fields=("class_group", "taken_on", "period"),
                name="one_register_per_group_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="register",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__gte", 1)),
                name="a_period_is_numbered_from_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancemark",
            constraint=models.UniqueConstraint(
                fields=("register", "student_membership_id"),
                name="one_mark_per_student_per_register",
            ),
        ),
    ]
